// Cloudflare Worker entry (wrangler.toml `main`): the worker OpenNext
// generates, plus a real Content-Length on library artifact downloads (see
// src/lib/library/fixed-length.ts). Build with `npm run cf:build` first; the
// imports below only exist after it.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import openNextWorker from "../.open-next/worker.js";
import { withFixedLength } from "./lib/library/fixed-length";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

type Worker = { fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> };

const worker = {
  async fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    const response = await (openNextWorker as Worker).fetch(request, env, ctx);
    const FixedLengthStream = (globalThis as { FixedLengthStream?: Parameters<typeof withFixedLength>[1] }).FixedLengthStream;
    return withFixedLength(response, FixedLengthStream);
  },
};

export default worker;
